package gear

const (
	MATERIA_TYPE_CRIT = iota
	MATERIA_TYPE_DETERMINATION
	MATERIA_TYPE_DIRECTHIT
	MATERIA_TYPE_SKILLSPEED
	MATERIA_TYPE_SPELLSPEED
	MATERIA_TYPE_TENACITY
	MATERIA_TYPE_PIETY
)

const (
	MATERIA_GRADE_I = iota
	MATERIA_GRADE_II
	MATERIA_GRADE_III
	MATERIA_GRADE_IV
	MATERIA_GRADE_V
	MATERIA_GRADE_VI
	MATERIA_GRADE_VII
	MATERIA_GRADE_VIII
	MATERIA_GRADE_IX
	MATERIA_GRADE_X
)

type Materia struct {
	Type  int
	Grade int
}
